name: PHP CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml
          tools: composer, php-cs-fixer, psalm

      - name: Validate composer.json and composer.lock
        working-directory: ./laravel
        run: composer validate

      - name: Install dependencies
        working-directory: ./laravel
        run: composer install --prefer-dist --no-progress --no-suggest

      # PHPCS
      - name: Check PSR-12 code standards
        working-directory: ./laravel
        run: ./vendor/bin/phpcs

      # Psalm
      - name: Run Psalm
        working-directory: ./laravel
        run: ./vendor/bin/psalm

      # Swagger
      - name: Run Test
        working-directory: ./laravel
        run: php artisan l5-swagger:generate

      # АвтоТесты
      - name: Run Test
        working-directory: ./laravel
        run: php artisan test --parallel
